zyu22/honeyboard-server

src/main/java/com/honeyboard/api/algorithm/guide/controller/AlgorithmGuideController.java, src/main/java/com/honeyboard/api/algorithm/guide/mapper/AlgorithmGuideMapper.java, src/main/java/com/honeyboard/api/algorithm/guide/model/AlgorithmGuide.java, src/main/java/com/honeyboard/api/algorithm/guide/service/AlgorithmGuideService.java, src/main/java/com/honeyboard/api/algorithm/guide/service/AlgorithmGuideServiceImpl.java, src/main/java/com/honeyboard/api/algorithm/problem/controller/AlgorithmProblemController.java, src/main/java/com/honeyboard/api/algorithm/problem/mapper/AlgorithmProblemMapper.java, src/main/java/com/honeyboard/api/algorithm/problem/model/AlgorithmProblem.java, src/main/java/com/honeyboard/api/algorithm/problem/service/AlgorithmProblemService.java, src/main/java/com/honeyboard/api/algorithm/problem/service/AlgorithmProblemServiceImpl.java, src/main/java/com/honeyboard/api/algorithm/solution/controller/AlgorithmSolutionController.java, src/main/java/com/honeyboard/api/algorithm/solution/mapper/AlgorithmSolutionMapper.java, src/main/java/com/honeyboard/api/algorithm/solution/model/AlgorithmSolution.java, src/main/java/com/honeyboard/api/algorithm/solution/service/AlgorithmSolutionService.java, src/main/java/com/honeyboard/api/algorithm/solution/service/AlgorithmSolutionServiceImpl.java, src/main/java/com/honeyboard/api/team/track/controller/TrackTeamController.java, src/main/java/com/honeyboard/api/team/track/model/TrackTeam.java, src/main/java/com/honeyboard/api/team/track/service/TrackTeamService.java
=> [Setting] 알고리즘 폴더구조 생성

pom.xml, src/main/java/com/honeyboard/api/pdf/Document.java, src/main/java/com/honeyboard/api/pdf/DocumentType.java, src/main/java/com/honeyboard/api/project/finale/controller/FinaleTeamController.java, src/main/java/com/honeyboard/api/project/finale/mapper/FinaleProjectMapper.java, src/main/java/com/honeyboard/api/project/finale/model/FinaleMember.java, src/main/java/com/honeyboard/api/project/finale/model/FinaleProjectBoard.java, src/main/java/com/honeyboard/api/project/finale/model/FinaleTeam.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamService.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamServiceImpl.java, src/main/resources/mapper/FinaleProjectMapper.xml
ref #13 
- OpenHTML to PDF 의존성 추가
- PDF Box 의존성 추가
어떤 변경 사항이 있나요?
=> [setting] 의존성 추가

src/main/java/com/honeyboard/api/algorithm/problem/controller/AlgorithmProblemController.java, src/main/java/com/honeyboard/api/algorithm/problem/mapper/AlgorithmProblemMapper.java, src/main/java/com/honeyboard/api/algorithm/problem/model/AlgorithmProblem.java, src/main/java/com/honeyboard/api/algorithm/problem/service/AlgorithmProblemService.java, src/main/java/com/honeyboard/api/algorithm/problem/service/AlgorithmProblemServiceImpl.java, src/main/java/com/honeyboard/api/algorithm/tag/controller/TagController.java, src/main/java/com/honeyboard/api/algorithm/tag/mapper/TagMapper.java, src/main/java/com/honeyboard/api/algorithm/tag/model/Tag.java, src/main/java/com/honeyboard/api/algorithm/tag/service/TagService.java, src/main/java/com/honeyboard/api/algorithm/tag/service/TagServiceImp.java, src/main/java/com/honeyboard/api/common/model/PageInfo.java, src/main/java/com/honeyboard/api/common/response/PageResponse.java, src/main/resources/mapper/AlgorithmProblemMapper.xml, src/main/resources/mapper/TagMapper.xml
closes #29 #9 
- 기존 요구사항에 search api와 getAll api을 별도로 분리해서 구현하라고 되어있으나, 검색관련 queryParam의 존재 여부에 따라 하나의 api로 유연하게 움직이는 것이 가능하다고 판단해 통합해서 구현
- pagenationd을 위한 PageInfo, PageResponse 구현, 공통으로 사용할 수 있는 class라 common 폴더 생성 후 안에 배치
- AlgorithmProblem 조회 시 Tag를 조회해야해서 추가로 Tag 관련 서비스가 구현이 필요했던 상황
- Tag 서비스 구현하는 김에 필요한 컨트롤러 (get, add)api 구현 및 서비스 구현
- Tag를 추가하면서 post, update 시 해당 알고리즘 태그 테이블에 같이 반영되도록 비즈니스로직 수정
- 원활한 디버깅을 위해 로그 추가
어떤 변경 사항이 있나요?
한번에 너무 많은 양이 올라가게 되어서 죄송해요!
관련 기능들이 다 연결되어 있는데 안되어있다보니 불가피 했던 점 양해바랍니다!
=> [feat] AlgorithmProblem, Tag, Pagenation 관련 기능 구현

src/main/java/com/honeyboard/api/project/track/controller/TrackProjectController.java, src/main/java/com/honeyboard/api/project/track/mapper/TrackProjectMapper.java, src/main/java/com/honeyboard/api/project/track/model/TrackProject.java, src/main/java/com/honeyboard/api/project/track/service/TrackProjectService.java, src/main/java/com/honeyboard/api/project/track/service/TrackProjectServiceImpl.java, src/main/resources/mapper/TrackProjectMapper.xml
- #15
closes [#15](https://github.com/zyu22/honeyboard-server/issues/15)
관통프로젝트와 관련된 API 생성
어떤 변경 사항이 있나요?
=> [Feat] 관통프로젝트 CRUD API 개발

src/main/java/com/honeyboard/api/config/SecurityConfig.java, src/main/java/com/honeyboard/api/handler/OAuth2AuthenticationSuccessHandler.java
- 소셜 로그인 성공시 리다이렉트 주소 변경
- 로그아웃 url 수정
어떤 변경 사항이 있나요?
=> [refactor] OAuth2 관련 수정

src/main/java/com/honeyboard/api/auth/controller/AuthController.java, src/main/java/com/honeyboard/api/auth/model/EmailVerification.java, src/main/java/com/honeyboard/api/auth/model/service/EmailServiceImpl.java, src/main/java/com/honeyboard/api/config/SecurityConfig.java, src/main/java/com/honeyboard/api/filter/JwtVerificationFilter.java, src/main/java/com/honeyboard/api/handler/CustomLogoutHandler.java, src/main/java/com/honeyboard/api/handler/LoginFailureHandler.java, src/main/java/com/honeyboard/api/handler/LoginSuccessHandler.java, src/main/java/com/honeyboard/api/handler/OAuth2AuthenticationSuccessHandler.java, src/main/java/com/honeyboard/api/user/model/service/UserDetailsServiceImpl.java, src/main/java/com/honeyboard/api/util/CookieUtil.java, src/main/resources/application-dev.properties, src/main/resources/application-prod.properties, src/main/resources/application.properties, src/main/resources/mapper/UserMapper.xml
- 디버깅을 위한 국문 로깅
- 프론트에서 요청받은 타입 안맞는 파일 수정
- oauth 리다이렉트 부분 수정
- 이메일 인증을 위한 로직 수정
- application.properties 내에서 모드 prod로 변경 시 개발환경에 맞은 auth 설정으로 변경
어떤 변경 사항이 있나요?
=> [refactor] 로그인, 이메일 인증 로직 수정

src/main/java/com/honeyboard/api/user/controller/UserController.java
=> [refactor] UserController/getUserInfo 수정

src/main/java/com/honeyboard/api/auth/controller/AuthController.java, src/main/java/com/honeyboard/api/chat/controller/ChatController.java, src/main/java/com/honeyboard/api/handler/LoginSuccessHandler.java, src/main/java/com/honeyboard/api/project/finale/model/FinaleMember.java, src/main/java/com/honeyboard/api/project/finale/model/FinaleProject.java, src/main/java/com/honeyboard/api/project/finale/model/FinaleProjectBoard.java, src/main/java/com/honeyboard/api/project/finale/model/FinaleTeam.java, src/main/java/com/honeyboard/api/user/controller/UserController.java, src/main/java/com/honeyboard/api/user/model/User.java, src/main/resources/mapper/UserMapper.xml
=> [refactor] UserMapper, UserController, ChatController 수정

src/main/java/com/honeyboard/api/auth/model/service/EmailServiceImpl.java, src/main/java/com/honeyboard/api/user/model/User.java, src/main/resources/application.properties
=> [refactor] User DTO 래퍼클래스 변경, Email UI 변경

src/main/java/com/honeyboard/api/chat/controller/ChatController.java, src/main/java/com/honeyboard/api/chat/controller/ChatWebSocketController.java, src/main/java/com/honeyboard/api/chat/mapper/ChatMapper.java, src/main/java/com/honeyboard/api/chat/service/ChatService.java, src/main/java/com/honeyboard/api/chat/service/ChatServiceImp.java, src/main/java/com/honeyboard/api/config/SecurityConfig.java, src/main/java/com/honeyboard/api/config/WebSocketConfig.java
- send 반환타입 수정
- SecurityConfig ws 요청 승인
어떤 변경 사항이 있나요?
=> [refactor] WebSocket chatting 버그수정 

src/main/java/com/honeyboard/api/project/track/controller/TrackProjectBoardController.java, src/main/java/com/honeyboard/api/project/track/mapper/TrackProjectBoardMapper.java, src/main/java/com/honeyboard/api/project/track/model/TrackProjectBoard.java, src/main/java/com/honeyboard/api/project/track/service/TrackProjectBoardService.java, src/main/java/com/honeyboard/api/project/track/service/TrackProjectBoardServiceImpl.java, src/main/resources/mapper/TrackProjectBoardMapper.xml
close #17 
관통 게시글 CRUD API 개발
어떤 변경 사항이 있나요?
=> [feat] 관통 게시글 CRUD API 개발

src/main/java/com/honeyboard/api/project/track/controller/TrackTeamController.java, src/main/java/com/honeyboard/api/project/track/service/TrackTeamServiceImpl.java, src/main/java/com/honeyboard/api/web/guide/controller/WebGuideController.java, src/main/java/com/honeyboard/api/web/guide/mapper/WebGuideMapper.java, src/main/java/com/honeyboard/api/web/guide/service/WebGuideService.java, src/main/java/com/honeyboard/api/web/guide/service/WebGuideServiceImpl.java, src/main/java/com/honeyboard/api/web/recommend/controller/WebRecommendController.java, src/main/java/com/honeyboard/api/web/recommend/mapper/WebRecommendMapper.java, src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendService.java, src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendServiceImpl.java, src/main/resources/application.properties, src/main/resources/mapper/WebGuideMapper.xml, src/main/resources/mapper/WebRecommendMapper.xml, src/test/java/com/honeyboard/api/web/guide/controller/WebGuideControllerTest.java, src/test/java/com/honeyboard/api/web/recommend/controller/WebRecommendControllerTest.java
=> [refactor] 웹 추천 Global Exception 핸들링 적용 및 Mapper 수정

src/main/java/com/honeyboard/api/schedule/model/Schedule.java, src/main/java/com/honeyboard/api/schedule/service/ScheduleServiceImpl.java, src/main/resources/mapper/ScheduleMapper.xml, src/test/java/com/honeyboard/api/schedule/controller/ScheduleControllerTest.java
ref #37 [Feat] 일정 CUD 및 캘린더 조회 API 개발
isPublic -> publicAccess로 변경
: 프론트에서 문제 생겨요
어떤 변경 사항이 있나요?
=> [Feat] 일정 CUD 및 캘린더 조회 API 개발

src/main/resources/mapper/FinaleTeamMapper.xml
- 팀 안 정해진 유저 가져올 때 id 같이 가져오게 수정
어떤 변경 사항이 있나요?
=> [refactor] 팀 안 정해진 유저 가져올 때 id 같이 가져오게 수정

src/main/java/com/honeyboard/api/auth/controller/AuthController.java, src/main/java/com/honeyboard/api/auth/service/CustomOAuth2UserService.java, src/main/java/com/honeyboard/api/auth/service/EmailService.java, src/main/java/com/honeyboard/api/auth/service/EmailServiceImpl.java, src/main/java/com/honeyboard/api/auth/service/VerificationService.java, src/main/java/com/honeyboard/api/auth/service/VerificationServiceImpl.java, src/main/java/com/honeyboard/api/auth/util/OAuth2UserInfoFactory.java, src/main/java/com/honeyboard/api/chat/controller/ChatWebSocketController.java, src/main/java/com/honeyboard/api/config/SecurityConfig.java, src/main/java/com/honeyboard/api/project/finale/controller/FinaleTeamController.java, src/main/java/com/honeyboard/api/user/controller/UserController.java, src/main/java/com/honeyboard/api/user/mapper/UserMapper.java, src/main/java/com/honeyboard/api/user/service/UserDetailsServiceImpl.java, src/main/java/com/honeyboard/api/user/service/UserService.java, src/main/java/com/honeyboard/api/user/service/UserServiceImpl.java, src/main/resources/mapper/UserMapper.xml
=> [refactor] directory 구조 변경

src/main/java/com/honeyboard/api/generation/controller/GenerationController.java, src/main/java/com/honeyboard/api/generation/service/GenerationService.java, src/main/java/com/honeyboard/api/generation/service/GenerationServiceImpl.java, src/main/java/com/honeyboard/api/user/controller/AdminController.java, src/main/java/com/honeyboard/api/user/mapper/AdminMapper.java, src/main/java/com/honeyboard/api/user/model/UserInfo.java, src/main/java/com/honeyboard/api/user/service/AdminService.java, src/main/java/com/honeyboard/api/user/service/AdminServiceimpl.java, src/main/resources/mapper/AdminMapper.xml, src/test/java/com/honeyboard/api/admin/controller/AdminControllerTest.java, src/test/java/com/honeyboard/api/generation/controller/GenerationControllerTest.java
=> [feat] 관리자 및 기수 API 개발

src/main/java/com/honeyboard/api/user/controller/AdminController.java, src/main/java/com/honeyboard/api/web/guide/controller/WebGuideController.java, src/main/java/com/honeyboard/api/web/recommend/controller/WebRecommendController.java, src/main/resources/mapper/AdminMapper.xml, src/main/resources/mapper/WebGuideMapper.xml, src/main/resources/mapper/WebRecommendMapper.xml
- WebRecommend recommend_id -> id
- Admin id -> userId
- 쿼리 Param require false 적용
- if null 을 활용해 쿼리 Param 없을 경우 전체 렌더링
어떤 변경 사항이 있나요?
=> [refactor] DB와 DTO 변수명 안맞는것 통일

src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamServiceImpl.java, src/main/java/com/honeyboard/api/web/guide/mapper/WebGuideMapper.java, src/main/java/com/honeyboard/api/web/guide/service/WebGuideServiceImpl.java, src/main/java/com/honeyboard/api/web/recommend/mapper/WebRecommendMapper.java, src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendServiceImpl.java, src/main/resources/mapper/FinaleTeamMapper.xml, src/main/resources/mapper/WebGuideMapper.xml, src/main/resources/mapper/WebRecommendMapper.xml, src/test/java/com/honeyboard/api/project/finale/controller/FinaleTeamControllerTest.java
=> [refactor] finaleTeam 오타 수정 및 테스트 추가

src/main/java/com/honeyboard/api/project/finale/controller/FinaleTeamController.java, src/main/java/com/honeyboard/api/project/finale/mapper/FinaleTeamMapper.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamService.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamServiceImpl.java, src/main/java/com/honeyboard/api/user/model/UserName.java, src/main/resources/mapper/FinaleTeamMapper.xml
Remained User 전달 시 UserDto에 넣으면 수많은 null 전달, userId와 name만 가지고 있는 UserName DTO 생성 후 반환타입으로 지정
어떤 변경 사항이 있나요?
=> [refactor] UserName dto 생성, remained user 전달 시 사용

.gitignore, .idea/compiler.xml, src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectController.java, src/main/java/com/honeyboard/api/user/controller/AdminController.java, src/main/resources/application.properties, src/main/resources/mapper/AdminMapper.xml, src/test/java/com/honeyboard/api/admin/controller/AdminControllerTest.java
=> [refactor] properties 추가 및 lombok 풀리던 문제 해결

src/main/java/com/honeyboard/api/user/controller/AdminController.java, src/main/java/com/honeyboard/api/user/service/AdminService.java, src/main/java/com/honeyboard/api/user/service/AdminServiceimpl.java
- 기수 등록 시 등록된 기수의 ID 값 반환
어떤 변경 사항이 있나요?
=> [refactor] ADMIN 쿼리 결과 반환

.gitignore, src/main/java/com/honeyboard/api/algorithm/guide/model/AlgorithmGuide.java, src/main/resources/mapper/AlgorithmGuideMapper.xml
=> [refactor] algorithmGuide 썸네일 추가로 mapper 및 model 수정, .gitignor 수정

.idea/compiler.xml, src/main/java/com/honeyboard/api/config/SecurityConfig.java, src/main/java/com/honeyboard/api/exception/DuplicateTeamMemberException.java, src/main/java/com/honeyboard/api/filter/JwtVerificationFilter.java, src/main/java/com/honeyboard/api/handler/GlobalExceptionHandler.java, src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectController.java, src/main/java/com/honeyboard/api/project/finale/controller/FinaleTeamController.java, src/main/java/com/honeyboard/api/project/finale/mapper/FinaleTeamMapper.java, src/main/java/com/honeyboard/api/project/finale/model/FinaleMember.java, src/main/java/com/honeyboard/api/project/finale/model/FinaleTeam.java, src/main/java/com/honeyboard/api/project/finale/model/FinaleTeamRequest.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamService.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamServiceImpl.java, src/main/resources/mapper/FinaleTeamMapper.xml, src/main/resources/mapper/TrackProjectBoardMapper.xml
- FinaleProject 관련 API FinaleProjectController로 이동
- FinaleTeam 및 FinaleProject 생성 로직 변경
어떤 변경 사항이 있나요?
=> [refactor] FinaleTeam 및 FinaleProject 관련 수정

src/main/resources/mapper/AlgorithmSolutionMapper.xml
ref #11 
AlgorithmSolution 상세보기에서 북마크 여부 확인에 문제 있어서 수정했습니다
어떤 변경 사항이 있나요?
=> [Refactor] AlgorithmSolution sql쿼리 수정

src/main/java/com/honeyboard/api/project/finale/model/FinaleProject.java, src/main/java/com/honeyboard/api/project/finale/model/FinaleProjectBoard.java, src/main/java/com/honeyboard/api/project/track/model/TrackProject.java, src/main/java/com/honeyboard/api/project/track/model/TrackProjectBoard.java, src/main/resources/mapper/FinaleProjectBoardMapper.xml, src/main/resources/mapper/FinaleProjectMapper.xml, src/main/resources/mapper/TrackProjectBoardMapper.xml, src/main/resources/mapper/TrackProjectMapper.xml
=> [refactor] 썸네일 추가로 Project들 mapper 및 model 수정

src/main/java/com/honeyboard/api/algorithm/guide/controller/AlgorithmGuideController.java, src/main/resources/mapper/FinaleTeamMapper.xml
- addAlgorithmGuide API generationId 안 받을 수 있게 수정
어떤 변경 사항이 있나요?
=> [refactor] AlgorithmGuideController 수정

src/main/java/com/honeyboard/api/algorithm/language/controller/ProgrammingLanguageController.java, src/main/java/com/honeyboard/api/algorithm/language/mapper/ProgrammingLanguageMapper.java, src/main/java/com/honeyboard/api/algorithm/language/model/ProgrammingLanguage.java, src/main/java/com/honeyboard/api/algorithm/language/service/ProgrammingLanguageService.java, src/main/java/com/honeyboard/api/algorithm/language/service/ProgrammingLanguageServiceImpl.java, src/main/java/com/honeyboard/api/exception/DuplicateVideoException.java, src/main/java/com/honeyboard/api/handler/GlobalExceptionHandler.java, src/main/java/com/honeyboard/api/youtube/service/YoutubeServiceImpl.java, src/main/resources/mapper/ProgrammingLanguageMapper.xml
ref #42 
유뷰브 영상 중복 저장의 에러핸들러 추가했습니다.
어떤 변경 사항이 있나요?
=> [Refactor] 유튜브영상상저장 에러핸들러 추가

.idea/compiler.xml, pom.xml, src/main/java/com/honeyboard/api/algorithm/guide/controller/AlgorithmGuideController.java, src/main/java/com/honeyboard/api/config/SecurityConfig.java, src/main/java/com/honeyboard/api/config/SwaggerConfig.java, src/main/java/com/honeyboard/api/config/WebConfig.java, src/main/java/com/honeyboard/api/filter/JwtVerificationFilter.java, src/main/java/com/honeyboard/api/pdf/service/PdfGeneratorServiceImpl.java, src/main/resources/application.properties
- Swagger 설정 추가(문서 만들던 건 지금 대공사가 이루어지는 중이라 디벨롭브랜치걸로 싹 덮고 올립니다
- PDF 서비스에서 try catch 구문 수정
어떤 변경 사항이 있나요?
=> [docs] Swagger 설정 추가

src/main/java/com/honeyboard/api/filter/JwtVerificationFilter.java
- access token이 만료되면 로그아웃 되는 현상 수정
- JwtVerificationFilter에 access token 검증 로직 추가
- JwtVerificationFilter에 rotate하는 메서드 구현(doFilter 메서드 안에서 밖으로)
어떤 변경 사항이 있나요?
=> [refactor] rtr 방식 수정

src/main/java/com/honeyboard/api/auth/service/VerificationServiceImpl.java, src/main/java/com/honeyboard/api/exception/BusinessException.java, src/main/java/com/honeyboard/api/exception/DuplicateEmailException.java, src/main/java/com/honeyboard/api/exception/DuplicateTeamMemberException.java, src/main/java/com/honeyboard/api/exception/DuplicateVideoException.java, src/main/java/com/honeyboard/api/exception/ErrorCode.java, src/main/java/com/honeyboard/api/exception/InvalidTokenException.java, src/main/java/com/honeyboard/api/exception/RefreshTokenNotFoundException.java, src/main/java/com/honeyboard/api/exception/TokenExpiredException.java, src/main/java/com/honeyboard/api/exception/VerificationCodeException.java, src/main/java/com/honeyboard/api/exception/VerificationCodeExpiredException.java, src/main/java/com/honeyboard/api/handler/GlobalExceptionHandler.java, src/main/java/com/honeyboard/api/jwt/model/service/JwtServiceImpl.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamServiceImpl.java, src/main/java/com/honeyboard/api/user/service/UserServiceImpl.java, src/main/java/com/honeyboard/api/youtube/service/YoutubeServiceImpl.java
close #99 
어떤 변경 사항이 있나요?
- ErrorCode를 Enum타입으로 지정하여 Custom된 에러만 사용 가능하게 함
=> [refactor] 예외 처리 구조 개선

pom.xml, src/main/java/com/honeyboard/api/bookmark/controller/BookmarkController.java, src/main/java/com/honeyboard/api/bookmark/mapper/BookmarkMapper.java, src/main/java/com/honeyboard/api/bookmark/model/BookmarkResponse.java, src/main/java/com/honeyboard/api/bookmark/service/BookmarkService.java, src/main/java/com/honeyboard/api/bookmark/service/BookmarkServiceImpl.java, src/main/java/com/honeyboard/api/pdf/controller/PdfController.java, src/main/java/com/honeyboard/api/pdf/model/Document.java, src/main/java/com/honeyboard/api/pdf/service/PdfGeneratorService.java, src/main/java/com/honeyboard/api/pdf/service/PdfGeneratorServiceImpl.java, src/main/java/com/honeyboard/api/project/finale/model/request/FinaleProjectCreate.java, src/main/java/com/honeyboard/api/user/controller/UserController.java, src/main/java/com/honeyboard/api/user/mapper/BookmarkMapper2.java, src/main/java/com/honeyboard/api/user/service/BookmarkService2.java, src/main/java/com/honeyboard/api/user/service/BookmarkServiceImpl2.java, src/main/resources/mapper/BookmarkMapper.xml, src/test/java/com/honeyboard/api/algorithm/guide/controller/AlgorithmGuideControllerTest.java, src/test/java/com/honeyboard/api/config/TestConfig.java, src/test/java/com/honeyboard/api/user/controller/UserControllerUnitTest.java
=> [refactor] 북마크 DTO 추가

src/main/java/com/honeyboard/api/bookmark/mapper/BookmarkMapper.java, src/main/java/com/honeyboard/api/generation/controller/GenerationController.java, src/main/java/com/honeyboard/api/generation/mapper/GenerationMapper.java, src/main/java/com/honeyboard/api/generation/model/GenerationList.java, src/main/java/com/honeyboard/api/generation/service/GenerationService.java, src/main/java/com/honeyboard/api/generation/service/GenerationServiceImpl.java, src/main/java/com/honeyboard/api/user/controller/AdminController.java, src/main/java/com/honeyboard/api/user/mapper/AdminMapper.java, src/main/java/com/honeyboard/api/user/service/AdminService.java, src/main/java/com/honeyboard/api/user/service/AdminServiceimpl.java, src/main/java/com/honeyboard/api/web/recommend/controller/WebRecommendController.java, src/main/java/com/honeyboard/api/web/recommend/mapper/WebRecommendMapper.java, src/main/java/com/honeyboard/api/web/recommend/model/request/WebRecommendRequest.java, src/main/java/com/honeyboard/api/web/recommend/model/response/WebRecommendDetail.java, src/main/java/com/honeyboard/api/web/recommend/model/response/WebRecommendList.java, src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendService.java, src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendServiceImpl.java, src/main/resources/mapper/BookmarkMapper.xml, src/test/java/com/honeyboard/api/admin/controller/AdminControllerTest.java, src/test/java/com/honeyboard/api/generation/controller/GenerationControllerTest.java, src/test/java/com/honeyboard/api/web/recommend/controller/WebRecommendControllerTest.java
ref #92 
close #96 
어떤 변경 사항이 있나요?
=> [refactor] 웹 추천 및 기수 DTO 리팩토링

src/main/java/com/honeyboard/api/exception/ErrorCode.java, src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectController.java, src/main/java/com/honeyboard/api/project/finale/mapper/FinaleProjectMapper.java, src/main/java/com/honeyboard/api/project/finale/model/response/FinaleProjectResponse.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectBoardService.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectBoardServiceImpl.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectService.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectServiceImpl.java, src/main/resources/mapper/FinaleProjectMapper.xml
- 모든 API 수정
- 모든 서비스 로직 수정
- 모든 MyBatis 로직 수정
어떤 변경 사항이 있나요?
=> [refactor] FinaleProject 관련 로직 수정

src/main/java/com/honeyboard/api/algorithm/problem/controller/AlgorithmProblemController.java, src/main/java/com/honeyboard/api/algorithm/problem/mapper/AlgorithmProblemMapper.java, src/main/java/com/honeyboard/api/algorithm/problem/service/AlgorithmProblemService.java, src/main/java/com/honeyboard/api/algorithm/problem/service/AlgorithmProblemServiceImpl.java, src/main/java/com/honeyboard/api/algorithm/solution/controller/AlgorithmSolutionController.java, src/main/java/com/honeyboard/api/algorithm/solution/mapper/AlgorithmSolutionMapper.java, src/main/java/com/honeyboard/api/algorithm/solution/model/response/AlgorithmSolutionDetail.java, src/main/java/com/honeyboard/api/algorithm/solution/service/AlgorithmSolutionService.java, src/main/java/com/honeyboard/api/algorithm/solution/service/AlgorithmSolutionServiceImpl.java, src/main/java/com/honeyboard/api/algorithm/tag/controller/TagController.java, src/main/java/com/honeyboard/api/algorithm/tag/mapper/TagMapper.java, src/main/java/com/honeyboard/api/algorithm/tag/service/TagService.java, src/main/java/com/honeyboard/api/algorithm/tag/service/TagServiceImp.java, src/main/resources/mapper/AlgorithmProblemMapper.xml, src/main/resources/mapper/TagMapper.xml
=> [Refactor] Algorithm Solution, Tag 주석처리

src/main/java/com/honeyboard/api/config/SecurityConfig.java, src/main/java/com/honeyboard/api/filter/JwtVerificationFilter.java, src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectBoardController.java, src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectController.java, src/main/java/com/honeyboard/api/project/finale/controller/FinaleTeamController.java, src/main/java/com/honeyboard/api/project/finale/mapper/FinaleProjectBoardMapper.java, src/main/java/com/honeyboard/api/project/finale/mapper/FinaleProjectMapper.java, src/main/java/com/honeyboard/api/project/finale/mapper/FinaleTeamMapper.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectBoardService.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectBoardServiceImpl.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectService.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectServiceImpl.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamService.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamServiceImpl.java, src/main/resources/mapper/FinaleProjectBoardMapper.xml, src/main/resources/mapper/FinaleProjectMapper.xml, src/main/resources/mapper/FinaleTeamMapper.xml, src/test/java/com/honeyboard/api/project/finale/controller/FinaleTeamControllerTest.java
- SecurityConfig .permitAll에 해당 엔드포인트 추가
- JwtVerificationFilter의 excludedUrls에 해당 엔드포인트 추가
어떤 변경 사항이 있나요?
=> [refactor] reset-password api 권한범위 수정

src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectBoardServiceImpl.java, src/main/java/com/honeyboard/api/user/controller/UserController.java
=> [refactor] reset-password api 유저Id 받아오는 로직 추가

src/main/java/com/honeyboard/api/user/controller/UserController.java
=> [refactor] reset-password password encoding 로직 추가

src/main/java/com/honeyboard/api/algorithm/language/controller/ProgrammingLanguageController.java, src/main/java/com/honeyboard/api/algorithm/language/mapper/ProgrammingLanguageMapper.java, src/main/java/com/honeyboard/api/algorithm/language/model/LanguageList.java, src/main/java/com/honeyboard/api/algorithm/language/service/ProgrammingLanguageService.java, src/main/java/com/honeyboard/api/algorithm/language/service/ProgrammingLanguageServiceImpl.java, src/main/java/com/honeyboard/api/chat/controller/ChatController.java, src/test/java/com/honeyboard/api/project/finale/controller/FinaleTeamControllerTest.java
=> [refactor] 프로그래밍언어 모델명 수정, Chat 컨벤션 맞추기

src/main/resources/mapper/ProgrammingLanguageMapper.xml
=> [refactor] ProgrammingLanguageMapper 수정

src/main/java/com/honeyboard/api/web/guide/model/response/WebGuideDetail.java
ex) close #91 
DTO 오기재 문제 수정
어떤 변경 사항이 있나요?
=> [Refactor] DTO 오류 수정

pom.xml
=> [refactor] 의존 삭제

src/main/java/com/honeyboard/api/exception/ErrorCode.java, src/main/java/com/honeyboard/api/project/track/controller/TrackProjectBoardController.java, src/main/java/com/honeyboard/api/project/track/controller/TrackProjectController.java, src/main/java/com/honeyboard/api/project/track/mapper/TrackProjectBoardMapper.java, src/main/java/com/honeyboard/api/project/track/mapper/TrackProjectMapper.java, src/main/java/com/honeyboard/api/project/track/model/request/TrackProjectBoardRequest.java, src/main/java/com/honeyboard/api/project/track/model/request/TrackProjectRequest.java, src/main/java/com/honeyboard/api/project/track/service/TrackProjectBoardServiceImpl.java, src/main/java/com/honeyboard/api/project/track/service/TrackProjectServiceImpl.java, src/main/java/com/honeyboard/api/web/recommend/controller/WebRecommendController.java, src/main/java/com/honeyboard/api/web/recommend/mapper/WebRecommendMapper.java, src/main/java/com/honeyboard/api/web/recommend/model/request/WebRecommendRequest.java, src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendServiceImpl.java, src/main/resources/mapper/TrackProjectBoardMapper.xml, src/main/resources/mapper/TrackProjectMapper.xml, src/main/resources/mapper/WebRecommendMapper.xml
=> [Refactor] 웹 추천 중복 추가

src/main/java/com/honeyboard/api/project/track/controller/TrackProjectBoardController.java
=> [refactor] 관통게시글 Url 수정

src/main/java/com/honeyboard/api/bookmark/controller/BookmarkController.java, src/main/java/com/honeyboard/api/bookmark/model/BookmarkListResponse.java, src/main/java/com/honeyboard/api/bookmark/model/ContentType.java, src/main/java/com/honeyboard/api/bookmark/service/BookmarkServiceImpl.java, src/main/java/com/honeyboard/api/exception/ErrorCode.java, src/main/java/com/honeyboard/api/project/track/service/TrackProjectBoardServiceImpl.java, src/main/java/com/honeyboard/api/project/track/service/TrackProjectServiceImpl.java, src/main/java/com/honeyboard/api/project/track/service/TrackTeamServiceImpl.java
=> [refactor] 관통프로젝트 에러처리 커스텀으로 변경

src/main/resources/mapper/FinaleProjectMapper.xml, src/test/java/com/honeyboard/api/project/finale/controller/FinaleProjectControllerTest.java, src/test/java/com/honeyboard/api/project/finale/controller/FinaleTeamControllerTest.java
=> [refactor] 파이널프로젝트 전체조회시 멤버 한명만 나오는 문제 수정

src/main/resources/mapper/FinaleTeamMapper.xml
=> [refactor] 피날레프로젝트 id 빼먹은거 수정

src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectController.java, src/main/java/com/honeyboard/api/project/finale/mapper/FinaleProjectMapper.java, src/main/java/com/honeyboard/api/project/finale/model/response/FinaleTeamList.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectServiceImpl.java, src/main/resources/mapper/FinaleProjectMapper.xml, src/main/resources/mapper/FinaleTeamMapper.xml
=> [refactor] 파이널프로젝트 팀 조회 시 하나만 나오던거 수정,

pom.xml, src/main/java/com/honeyboard/api/config/RedisConfig.java, src/main/java/com/honeyboard/api/config/SecurityConfig.java, src/main/java/com/honeyboard/api/filter/JwtVerificationFilter.java, src/main/resources/application-dev.properties
=> [refactor] 리프레쉬토큰을 이용한 액세스토큰 재발급 로직 수정

src/main/java/com/honeyboard/api/algorithm/solution/service/AlgorithmSolutionServiceImpl.java, src/main/resources/mapper/AlgorithmSolutionMapper.xml
=> [Fix] AlgorithmSolution 페이지네이션 수정

src/main/java/com/honeyboard/api/user/service/MyPageServiceImpl.java, src/main/resources/application-dev.properties
=> [refactor] HikariCP 설정 추가

src/main/java/com/honeyboard/api/project/track/model/response/TrackProjectBoardDetail.java, src/main/java/com/honeyboard/api/project/track/model/response/TrackProjectBoardList.java, src/main/resources/mapper/TrackProjectBoardMapper.xml, src/main/resources/mapper/TrackProjectMapper.xml
=> [refactor] 관통 프로젝트 상세조회 팀 이름 안나오던거 수정

src/main/resources/mapper/TrackProjectBoardMapper.xml
=> [refactor] 실행 안되던거 수정

src/main/resources/mapper/AlgorithmSolutionMapper.xml, src/main/resources/mapper/WebGuideMapper.xml
=> [Refactor] 웹 개념, 추천 에서 오타, 소문자 수정

src/main/java/com/honeyboard/api/project/track/controller/TrackProjectBoardController.java, src/main/java/com/honeyboard/api/project/track/mapper/TrackProjectBoardMapper.java, src/main/java/com/honeyboard/api/project/track/service/TrackProjectBoardService.java, src/main/java/com/honeyboard/api/project/track/service/TrackProjectBoardServiceImpl.java, src/main/java/com/honeyboard/api/web/guide/controller/WebGuideController.java, src/main/java/com/honeyboard/api/web/guide/model/request/WebGuideRequest.java, src/main/java/com/honeyboard/api/web/guide/service/WebGuideServiceImpl.java, src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendServiceImpl.java, src/main/resources/mapper/WebGuideMapper.xml, src/main/resources/mapper/WebRecommendMapper.xml, src/test/java/com/honeyboard/api/web/guide/controller/WebGuideControllerTest.java
=> [Refactor] 웹 개념 생성된 게시글 반환 안되던거 수정

src/main/java/com/honeyboard/api/project/track/controller/TrackProjectBoardController.java, src/main/resources/mapper/WebGuideMapper.xml
=> [Refactor] 오타 수정

src/main/java/com/honeyboard/api/algorithm/tag/controller/TagController.java, src/main/java/com/honeyboard/api/algorithm/tag/mapper/TagMapper.java, src/main/java/com/honeyboard/api/algorithm/tag/service/TagService.java, src/main/java/com/honeyboard/api/algorithm/tag/service/TagServiceImp.java, src/main/resources/mapper/TagMapper.xml
=> [Refactor] Tag 수정

src/main/resources/mapper/AlgorithmGuideMapper.xml
=> [Refactor] 웹 개념 검색 수정

src/main/java/com/honeyboard/api/config/SecurityConfig.java, src/main/java/com/honeyboard/api/web/guide/controller/WebGuideController.java, src/main/resources/application-dev.properties, src/main/resources/application-prod.properties, src/main/resources/application.properties
=> [Refactor] properties prod로 변경, 웹개념 CUD 관리자만 할 수 있게 변경

src/main/java/com/honeyboard/api/algorithm/tag/controller/TagController.java, src/main/java/com/honeyboard/api/algorithm/tag/mapper/TagMapper.java, src/main/java/com/honeyboard/api/algorithm/tag/service/TagService.java, src/main/java/com/honeyboard/api/algorithm/tag/service/TagServiceImp.java, src/main/resources/mapper/AlgorithmProblemMapper.xml, src/main/resources/mapper/TagMapper.xml
=> [Refactor] Tag 검색 추가, AlgorithmProblem 검색 문제 수정

.github/workflows/main.yml
=> [docs] CICD를 위한 main.yml 파일 생성

.github/workflows/main.yml
=> [Refactor] 배포위한 main.yml 수정

Dockerfile
배포를 위한 Dockerfile 작성
어떤 변경 사항이 있나요?
=> [docs] Dockerfile 작성

.github/workflows/main.yml
=> [docs] main.yml 수정

src/main/resources/application.properties
=> [Docs] properies prod로 변경

src/main/java/com/honeyboard/api/auth/controller/AuthController.java, src/main/resources/application.properties
=> [refactor] 이메일 인증메일 발송 api verification 수정

src/main/resources/application-prod.properties
=> [Deploy] properties 변경 / 이메일 인증 api 변경

src/main/java/com/honeyboard/api/algorithm/tag/service/TagServiceImp.java
=> [Refactor] tag 검색 null 반환으로 수정

src/main/resources/mapper/MyPageMapper.xml, src/main/resources/mapper/TrackProjectMapper.xml
=> [Refactor] 마이페이지 프로젝트 쿼리 수정 및 트랙프로젝트 상세조회 삭제된 글 안나오게 수정

src/main/java/com/honeyboard/api/config/SecurityConfig.java, src/main/java/com/honeyboard/api/exception/ErrorCode.java, src/main/java/com/honeyboard/api/project/track/mapper/TrackProjectBoardMapper.java, src/main/java/com/honeyboard/api/project/track/model/response/TrackProjectDetail.java, src/main/java/com/honeyboard/api/project/track/service/TrackProjectBoardServiceImpl.java, src/main/java/com/honeyboard/api/user/service/MyProjectService.java, src/main/resources/mapper/TrackProjectBoardMapper.xml, src/main/resources/mapper/TrackProjectMapper.xml
=> [Refactor] SecurityConfig 수정(관리자), 트랙프로젝트 생성 시 팀 제출현황 조회 되게 변경

src/main/java/com/honeyboard/api/project/track/controller/TrackProjectController.java, src/main/java/com/honeyboard/api/project/track/service/TrackProjectServiceImpl.java, src/main/java/com/honeyboard/api/user/model/mypage/MyTrackProjectList.java, src/main/resources/mapper/MyPageMapper.xml, src/main/resources/mapper/TrackProjectMapper.xml
=> [Refactor] 관통프로젝트 관련 수정

src/main/java/com/honeyboard/api/exception/ErrorCode.java, src/main/java/com/honeyboard/api/project/track/mapper/TrackProjectMapper.java, src/main/java/com/honeyboard/api/project/track/service/TrackProjectServiceImpl.java, src/main/java/com/honeyboard/api/user/controller/AdminController.java, src/main/java/com/honeyboard/api/user/mapper/AdminMapper.java, src/main/java/com/honeyboard/api/user/model/mypage/MyTrackProjectList.java, src/main/java/com/honeyboard/api/user/service/AdminServiceimpl.java, src/main/resources/mapper/AdminMapper.xml, src/main/resources/mapper/MyPageMapper.xml, src/main/resources/mapper/TrackProjectMapper.xml
=> [Refactor] MyTrackProjectList에 boardId, trackTeamId, trackProjectId 추가

src/main/java/com/honeyboard/api/HoneyboardApplication.java, src/main/resources/mapper/TrackProjectMapper.xml
=> [Feat] TimeZone 설정 추가

src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectBoardServiceImpl.java
=> [refactor] delete API에 관리자도 수정 가능하게 수정

src/main/java/com/honeyboard/api/bookmark/controller/BookmarkController.java, src/main/java/com/honeyboard/api/bookmark/service/BookmarkService.java, src/main/java/com/honeyboard/api/bookmark/service/BookmarkServiceImpl.java, src/main/java/com/honeyboard/api/user/mapper/MyPageMapper.java, src/main/resources/mapper/FinaleTeamMapper.xml, src/main/resources/mapper/MyPageMapper.xml
=> [Refactor] 요구사항 수정

src/main/java/com/honeyboard/api/bookmark/controller/BookmarkController.java, src/main/java/com/honeyboard/api/bookmark/model/BookmarkListResponse.java, src/main/java/com/honeyboard/api/bookmark/service/BookmarkServiceImpl.java
=> [refactor] 북마크 반환 변수명 수정

src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectBoardServiceImpl.java, src/main/resources/mapper/FinaleProjectBoardMapper.xml
=> [Bugfix] 파이널 보드 삭제된 것 안 가져오게 수정

src/main/resources/mapper/FinaleProjectBoardMapper.xml
=> [Bugfix] 삭제 안 된걸 가져오게 수정

src/main/resources/mapper/AdminMapper.xml
=> [Bugfix] 관리자 유저 조회 시 기수역순, 이름순 정렬으로 수정

src/main/java/com/honeyboard/api/project/finale/controller/FinaleTeamController.java, src/main/java/com/honeyboard/api/project/finale/mapper/FinaleTeamMapper.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamService.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamServiceImpl.java, src/main/java/com/honeyboard/api/project/track/controller/TrackTeamController.java, src/main/java/com/honeyboard/api/project/track/mapper/TrackTeamMapper.java, src/main/java/com/honeyboard/api/project/track/service/TrackProjectBoardServiceImpl.java, src/main/java/com/honeyboard/api/project/track/service/TrackTeamService.java, src/main/java/com/honeyboard/api/project/track/service/TrackTeamServiceImpl.java, src/main/java/com/honeyboard/api/user/model/mypage/MyFinaleProjectList.java, src/main/resources/application-prod.properties, src/main/resources/mapper/FinaleTeamMapper.xml, src/main/resources/mapper/MyPageMapper.xml, src/main/resources/mapper/TrackTeamMapper.xml
=> [Feat] 관통 프로젝트 팀 생성 시 팀원이 있거나 제외인원에 있으면 검색 안되는 기능 추가

src/main/resources/mapper/WebGuideMapper.xml
웹 개념 관리자 본인이 작성한 게시글이 아닌 경우 수정 불가 -> 매퍼파일 변경
어떤 변경 사항이 있나요?
=> [fix]웹 개념 관리자 본인이 작성한 게시글이 아닌 경우 수정 불가

src/main/java/com/honeyboard/api/project/track/controller/TrackProjectController.java, src/main/java/com/honeyboard/api/project/track/mapper/TrackProjectMapper.java, src/main/java/com/honeyboard/api/project/track/service/TrackProjectService.java, src/main/java/com/honeyboard/api/project/track/service/TrackProjectServiceImpl.java, src/main/resources/mapper/TrackProjectMapper.xml
=> [feat] 트랙프로젝트 제외인원 조회 API 구현

src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectBoardController.java, src/main/java/com/honeyboard/api/project/track/service/TrackProjectBoardServiceImpl.java, src/main/java/com/honeyboard/api/web/recommend/controller/WebRecommendController.java, src/main/java/com/honeyboard/api/web/recommend/mapper/WebRecommendMapper.java, src/main/java/com/honeyboard/api/web/recommend/model/response/WebRecommendDetail.java, src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendService.java, src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendServiceImpl.java, src/main/resources/mapper/TrackProjectBoardMapper.xml, src/main/resources/mapper/WebRecommendMapper.xml
=> [Refactor] QA - 웹 추천 및 관통 수정사항 완료

src/main/java/com/honeyboard/api/schedule/controller/ScheduleController.java, src/main/java/com/honeyboard/api/schedule/mapper/ScheduleMapper.java, src/main/java/com/honeyboard/api/schedule/service/ScheduleService.java, src/main/java/com/honeyboard/api/schedule/service/ScheduleServiceImpl.java, src/main/resources/mapper/ScheduleMapper.xml
=> [Refactor] 일정 등록시 id 반환되지 않도록 수정, Track -> TRACK

src/main/resources/mapper/TrackProjectMapper.xml
- Mapper 관련해서 오타 나있는 부분 수정했습니다.
어떤 변경 사항이 있나요?
=> [bugfix]: Mapper 관련해서 오타 나있는 부분 수정

src/main/java/com/honeyboard/api/algorithm/problem/mapper/AlgorithmProblemMapper.java, src/main/java/com/honeyboard/api/algorithm/problem/model/response/AlgorithmProblemDetail.java, src/main/java/com/honeyboard/api/algorithm/problem/service/AlgorithmProblemServiceImpl.java, src/main/resources/mapper/AlgorithmProblemMapper.xml, src/main/resources/mapper/AlgorithmSolutionMapper.xml, src/main/resources/mapper/MyPageMapper.xml
=> [Refactor] Algorithm Problem - 기존 문제가 삭제되면 중복 url 허용

src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectController.java, src/main/java/com/honeyboard/api/project/finale/mapper/FinaleProjectMapper.java, src/main/java/com/honeyboard/api/project/finale/model/request/FinaleProjectCreate.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectService.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectServiceImpl.java, src/main/resources/application.properties, src/main/resources/mapper/FinaleProjectMapper.xml, src/test/java/com/honeyboard/api/project/finale/controller/FinaleTeamControllerTest.java
=> [refactor] 피날레 보드 생성 수정

src/main/java/com/honeyboard/api/project/finale/controller/FinaleTeamController.java, src/main/java/com/honeyboard/api/project/finale/mapper/FinaleTeamMapper.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamService.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamServiceImpl.java, src/main/resources/application.properties, src/main/resources/mapper/FinaleTeamMapper.xml
=> [refactor] 피날레 프로젝트 팀 수정 로직 수정

src/main/java/com/honeyboard/api/algorithm/problem/mapper/AlgorithmProblemMapper.java, src/main/java/com/honeyboard/api/algorithm/problem/service/AlgorithmProblemServiceImpl.java, src/main/resources/mapper/AlgorithmProblemMapper.xml
=> [Refactor] Algorithm Problem 문제수정 중복url확인 수정

src/main/java/com/honeyboard/api/auth/controller/AuthController.java
=> [feat] Add api for checking existing email

src/test/java/com/honeyboard/api/project/track/TrackProjectIntegrationTest.java
=> [Refactor] 명칭 변경으로 테스트에서 에러나던거 수정

src/main/java/com/honeyboard/api/project/finale/mapper/FinaleTeamMapper.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectServiceImpl.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamServiceImpl.java, src/main/resources/mapper/FinaleTeamMapper.xml
=> [bugfix] 파이널 프로젝트 팀 정보 가져오기

src/main/java/com/honeyboard/api/exception/ErrorCode.java, src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectController.java, src/main/java/com/honeyboard/api/project/finale/mapper/FinaleProjectMapper.java, src/main/java/com/honeyboard/api/project/finale/mapper/FinaleTeamMapper.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectService.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectServiceImpl.java, src/main/resources/mapper/FinaleProjectMapper.xml, src/main/resources/mapper/FinaleTeamMapper.xml
=> [Feat] 파이널프로젝트 물리적삭제로 변경 및 삭제 시 팀 삭제 기능 추가

src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendServiceImpl.java, src/main/resources/mapper/TrackProjectMapper.xml
=> [Refactor] 관통프로젝트 상세보기 시 팀장이 이름 먼저오게 수정

src/main/java/com/honeyboard/api/user/service/AdminServiceimpl.java, src/main/java/com/honeyboard/api/web/recommend/mapper/WebRecommendMapper.java, src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendServiceImpl.java, src/main/resources/mapper/WebRecommendMapper.xml
=> [Refactor] 요청사항 수정

src/main/java/com/honeyboard/api/project/track/mapper/TrackTeamMapper.java, src/main/java/com/honeyboard/api/project/track/service/TrackTeamServiceImpl.java, src/main/resources/mapper/TrackTeamMapper.xml
=> [Refactor] 관통에서 팀원이 팀장 수정 시 팀장 사라지던 문제 해결

src/main/java/com/honeyboard/api/project/finale/mapper/FinaleTeamMapper.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectServiceImpl.java, src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamServiceImpl.java, src/main/resources/mapper/FinaleTeamMapper.xml
파이널 프로젝트에서 프론트에서 전달되는 기수 파라미터를 활용해 참여 인원과 제출 현황 반환하도록 수정
어떤 변경 사항이 있나요?
=> [Refactor] 파이널 프로젝트 참여 인원 조회 불가 수정

src/main/resources/mapper/FinaleTeamMapper.xml
제출 현황과 팀 생성 시 멤버 조회에서 재적 인원이 조회되지 않도록 필터 추가
어떤 변경 사항이 있나요?
=> [refactor] 재적 인원 제외 후 조회되도록 필터 추가
